### ISSUE TITLE
Write function(s) to retrieve additional metrics

### ISSUE THREAD

**Issue by ahamidi** [140proof/OSS-health#13]
Additional metrics:
- [x] Has Wiki
- [x] Has Issues
- [x] Commit Activity
- [x] Participation

**Comment by shawnohare** [comment]
The ListParticipation function from the github package returns the weekly commit totals for the past year for both the entire repo and only the owner.  This data is sufficient to produce the output of the GetCommitStats function we currently have, so the GetParticipationStats subsumes GetCommitStats.  If we want more fine-grained commit data I guess we can keep GetCommitStats arround, otherwise I suggest we delete it.  I think the day-by-day commit activity variance is too high to really do much with.

**Comment by ahamidi** [comment]
I think we can just drop the ActivityStats and go with the participation stats.

**Comment by ahamidi** [comment]
I've removed ActivityStats and will create a pull request for this.
